version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias..."
      - npm install

  build:
    commands:
      - echo "Compilando TypeScript..."
      - npm run build
      - echo "Instalando dependencias de produccion..."
      - rm -rf node_modules
      - npm install --omit=dev
      - echo "Copiando node_modules a dist..."
      - cp -r node_modules dist/
      - echo "Empaquetando ZIP..."
      - cd dist
      - zip -r ../books-api.zip .
      - cd ..
      - echo "ZIP creado correctamente"
      - ls -lh books-api.zip

  post_build:
    commands:
      - echo "Desplegando en Lambda..."
      - aws lambda update-function-code
          --function-name api-books
          --zip-file fileb://books-api.zip
          --region us-east-1
      - echo "Deploy completado exitosamente"